### ISSUE TITLE
translation?

### ISSUE THREAD

**Issue by zhenyusun** [husseycoding/backorder#15]
where can we make the translation to another language for "dispatched if ordered within". I found the text in \app\design\frontend\base\default\template\backorder\estimate.phtml. But I wansn't able to change text for "hours" and "minutes".

**Comment by husseycoding** [comment]
All of the text in the extension passes through translation so you can alter it using any of the normal Magento translation methods (there are loads of tutorials around).  The text strings which can be translated are as follows:

Estimated dispatch
Dispatched today if ordered within the next
Dispatched tomorrow if ordered within the next
Dispatched on
I understand this product will be delayed
