### ISSUE TITLE
Backorder Lead Time is Being Ignored

### ISSUE THREAD

**Issue by youlogix** [husseycoding/backorder#16]
It seems that backorder lead time defined for product is being ignored or may be it needs to be filled in a particular format.

![chrome_2016-05-28_02-37-42](https://cloud.githubusercontent.com/assets/9247453/15621348/f1ded4b2-247d-11e6-81d3-bc11a4b82a82.png)
![chrome_2016-05-28_02-37-03](https://cloud.githubusercontent.com/assets/9247453/15621350/f1e23fda-247d-11e6-93ed-1a21c76e9bd4.png)
![chrome_2016-05-28_02-37-30](https://cloud.githubusercontent.com/assets/9247453/15621349/f1e0c254-247d-11e6-933a-53069a3d656b.png)
Refer attached screenshot.

**Comment by husseycoding** [comment]
Here I would say that '3-5 business days' is not valid.  The extension automatically only counts week days and you can't enter a range like that, so there you would enter 5 days.  The lead time of '1 week' is fine
