### ISSUE TITLE
DYNAMIC HOLIDAYS AND TRANSLATION

### ISSUE THREAD

**Issue by GILHE76** [husseycoding/backorder#6]
Hi, I have installed back order on a magento website, I would like to translate the date in french and also change weekends date to sunday, monday. Could you help me? thank you in advance, regards

**Comment by husseycoding** [comment]
Easier said than done unfortunately as PHP itself defines the weekend as Saturday and Sunday, but start with `class HusseyCoding_Backorder_Helper_Data` and method `_getEstimateString()`.  You'll need to edit reference to `> 5` for the weekend, `+1 weekday` and other date manipulation logic in that and all methods referenced i.e. `_setDateAfterHolidays()`, `_getHolidayDates()`.

To edit the date format look at class `_createDateString()`.
